# Generated by Django 6.0.2 on 2026-03-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_account_status_user_approval_status_and_more'),
        ('location', '0002_state_region_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email updates about new articles in your city')),
                ('breaking_news_alerts', models.BooleanField(default=True, help_text='Get instant notifications for breaking news')),
                ('weekly_newsletter', models.BooleanField(default=True, help_text='Receive a weekly digest of top stories')),
                ('article_recommendations', models.BooleanField(default=True, help_text='Article Recommendations')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
