# Generated by Django 6.0.2 on 2026-03-29 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_profile_image_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=255)),
                ('press_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_publications', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('aadhaar_file', models.FileField(upload_to='journalist_docs/aadhaar/')),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='journalist_docs/portfolio/')),
                ('press_card_file', models.FileField(blank=True, null=True, upload_to='journalist_docs/press_card/')),
                ('recommendation_file', models.FileField(blank=True, null=True, upload_to='journalist_docs/recommendation/')),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('portfolio_verified', models.BooleanField(default=False)),
                ('press_card_verified', models.BooleanField(default=False)),
                ('recommendation_verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journalist_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journalist_application',
            },
        ),
    ]
