# Generated by Django 6.0.2 on 2026-03-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_journalistapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalistapplication',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='journalistapplication',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='journalistapplication',
            name='press_card_number',
        ),
        migrations.RemoveField(
            model_name='journalistapplication',
            name='previous_publications',
        ),
        migrations.RemoveField(
            model_name='journalistapplication',
            name='specialization',
        ),
    ]
