# Generated by Django 6.0.2 on 2026-03-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='journalistapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
