# Generated by Django 6.0.2 on 2026-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='region_type',
            field=models.CharField(choices=[('state', 'State'), ('ut', 'Union Territory')], default='state', max_length=10),
        ),
    ]
