# Generated by Django 6.0.2 on 2026-04-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_adreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenreport',
            old_name='description',
            new_name='reason',
        ),
    ]
