# Generated by Django 6.0.2 on 2026-03-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_category_created_at_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
