# Generated by Django 6.0.2 on 2026-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Save as Draft'), ('published', 'Publish immediately')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='articlemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image')], default='image', max_length=10),
        ),
    ]
