# Generated by Django 6.0.2 on 2026-03-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_article_publication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_article',
            name='is_draft',
        ),
    ]
