# Generated by Django 6.0.2 on 2026-03-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_article_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_article',
            name='state_id',
        ),
    ]
