# Generated by Django 6.0.2 on 2026-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_article_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='approved', max_length=20),
        ),
    ]
