# Generated by Django 6.0.2 on 2026-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_article',
            name='publication_status',
        ),
        migrations.AlterField(
            model_name='news_article',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='approved', max_length=20),
        ),
    ]
