# Generated by Django 6.0.2 on 2026-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_savedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
