# Generated by Django 6.0.2 on 2026-03-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_article_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemedia',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news_article'),
        ),
    ]
