# Generated by Django 6.0.2 on 2026-03-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_articlemedia_article_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='savedarticle',
            table='saved_article',
        ),
    ]
