# Generated by Django 6.0.2 on 2026-04-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemedia',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlemedia',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlemedia',
            name='file_url',
            field=models.TextField(default=''),
        ),
    ]
