from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.homePage, name='home'),
    path('signup/', views.userSignupView, name='signup'), 
    path('signup/verify/', views.signupVerifyOTPView, name='signup_verify_otp'), 
    path('login/', views.userLoginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    
    # New Password Reset Flow
    path('password_reset/', views.forgotPasswordView, name='password_reset'),
    path('password_reset/verify/', views.verifyOTPView, name='verify_otp'),
    path('password_reset/new-password/', views.resetPasswordView, name='reset_password'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'), name='password_reset_complete'),

    path('adminpanel/dashboard/', views.adminPanelDashboardView, name='admin_panel_dashboard'),
    path('adminpanel/applications/', views.adminPanelApplicationsView, name='admin_panel_applications'),
    path('adminpanel/applications/approve/<int:id>', views.adminPanelApplicationsApproval, name='admin_panel_applications_approval'),
    path('adminpanel/applications/reject/<int:id>', views.adminPanelApplicationsReject, name='admin_panel_applications_reject'),
    path('adminpanel/applications/preview/<int:id>', views.adminPanelApplicationPreviewView, name='admin_panel_applications_preview'),
    path('adminpanel/journalists/', views.adminPanelJournalistsView, name='admin_panel_journalists'),
    path('adminpanel/advertisers/', views.adminPanelAdvertisersView, name='admin_panel_advertisers'),
    path('adminpanel/readers/', views.adminPanelReadersView, name='admin_panel_readers'),
    path('adminpanel/payments/', views.adminPanelPaymentsView, name='admin_panel_payments'),
    path('adminpanel/articles/', views.adminPanelArticlesView, name='admin_panel_articles'),
    path('adminpanel/articles/approve/<int:id>', views.adminPanelArticleApproveView, name='admin_panel_article_approve'),
    path('adminpanel/articles/reject/<int:id>', views.adminPanelArticleRejectView, name='admin_panel_article_reject'),
    path('adminpanel/articles/delete/<int:id>', views.adminPanelArticleDeleteView, name='admin_panel_article_delete'),
    path('adminpanel/comments/', views.adminPanelCommentsView, name='admin_panel_comments'),
    path('adminpanel/comments/block/<int:id>', views.adminPanelCommentBlockView, name='admin_panel_comment_block'),
    path('adminpanel/comments/unblock/<int:id>', views.adminPanelCommentUnblockView, name='admin_panel_comment_unblock'),
    path('adminpanel/comments/delete/<int:id>', views.adminPanelCommentDeleteView, name='admin_panel_comment_delete'),
    path('adminpanel/ads/', views.adminPanelAdsView, name='admin_panel_ads'),
    path('adminpanel/ads/block/<int:id>', views.adminPanelAdBlockView, name='admin_panel_ads_block'),
    path('adminpanel/ads/unblock/<int:id>', views.adminPanelAdUnblockView, name='admin_panel_ads_unblock'),
    path('adminpanel/ads/delete/<int:id>', views.adminPanelAdDeleteView, name='admin_panel_ads_delete'),
    path('adminpanel/users/block/<int:id>', views.adminPanelUserBlockView, name='admin_panel_user_block'),
    path('journalist/apply/', views.journalistApplicationView, name='journalist_application'),
    path('journalist/pending/', views.journalistPendingView, name='journalist_pending'),
    path('journalist/withdraw/', views.journalistWithdrawView, name='journalist_withdraw'),
    path('reader/dashboard/', views.readerDashboardView, name='reader_dashboard'),
    path('reader/saved/', views.readerSavedArticlesView, name='reader_saved_articles'),
    path('reader/unsave/<int:article_id>/', views.readerUnsaveArticleView, name='reader_unsave_article'),
    path('reader/profile/', views.readerProfileView, name='reader_profile'),
    path('reader/general/', views.readerGeneralView, name='reader_general'),
    path('article/<slug:slug>/record-view/', views.recordArticleView, name='article_record_view'),
    path('article/<slug:slug>/', views.articleDetailView, name='article_detail'),
    path('article/comment/<int:article_id>/', views.addCommentView, name='add_comment'),
    path('latest/', views.latestStoriesView, name='latest_stories'),
    path('search/', views.searchResultsView, name='search'),

    path('category/<slug:slug>/', views.categoryArticlesView, name='category_articles'),
    path('state-politics/', views.statePoliticsView, name='state_politics'),
    path('article/save/<int:article_id>/', views.saveArticleView, name='save_article'),
    path('article/report/<int:article_id>/', views.reportArticleView, name='report_article'),
    path('ad/report/<int:ad_id>/', views.reportAdView, name='report_ad'),
    path('comment/report/<int:comment_id>/', views.reportCommentView, name='report_comment'),
    path('adminpanel/applications/document-action/<int:user_id>/<str:doc_slug>/<str:action>/', views.adminPanelDocumentActionView, name='admin_panel_document_action'),
    path('article/read/<int:article_id>/', views.read_article_tts_view, name='read_article_tts'),
]

