# Generated by Django 6.0.2 on 2026-03-31 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('gst_number', models.CharField(max_length=50)),
                ('budget_range', models.CharField(max_length=100)),
                ('campaign_duration', models.CharField(max_length=100)),
                ('target_cities', models.TextField(help_text='Comma-separated cities')),
                ('ad_format_preference', models.TextField(blank=True, help_text='Comma-separated formats', null=True)),
                ('campaign_objectives', models.TextField()),
                ('registration_certificate', models.FileField(upload_to='advertiser_docs/registration/')),
                ('gst_certificate', models.FileField(upload_to='advertiser_docs/gst/')),
                ('pan_card', models.FileField(upload_to='advertiser_docs/pan/')),
                ('bank_details', models.FileField(upload_to='advertiser_docs/bank/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertiser_application',
            },
        ),
    ]
