# Generated by Django 6.0.2 on 2026-04-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertiserapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserapplication',
            name='bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertiserapplication',
            name='gst_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertiserapplication',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertiserapplication',
            name='registration_verified',
            field=models.BooleanField(default=False),
        ),
    ]
