# Generated by Django 6.0.2 on 2026-04-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_advertiserapplication_bank_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_format',
            field=models.CharField(choices=[('Banner', 'Banner image'), ('Video', 'Video ad')], default='Banner', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/media/'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
