# Generated by Django 6.0.2 on 2026-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advertisement_ad_format_advertisement_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Duration in minutes (e.g., 5, 10, 15...)'),
        ),
    ]
