# Generated by Django 6.0.2 on 2026-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_advertisement_amount_advertisement_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('Homepage', 'Homepage'), ('Article Details Middle', 'Article Details Middle'), ('Article Details Left Sidebar', 'Article Details Left Sidebar'), ('Article Details Right Sidebar', 'Article Details Right Sidebar')], default='Homepage', max_length=50),
        ),
    ]
