# Generated by Django 6.0.2 on 2026-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_advertisement_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('Homepage Middle', 'Homepage Middle'), ('Homepage Sidebar', 'Homepage Sidebar'), ('Article Details Middle', 'Article Details Middle'), ('Article Details Sidebar', 'Article Details Sidebar')], default='Homepage Middle', max_length=50),
        ),
    ]
